### PR TITLE
deps: update swc to 1.7.5

### PR DESCRIPTION
**Pull request by marco-ippolito**
This PR:

- Adds the `--locked` flag to cargo install, so it will download from the lock file.
- removes crates from source since we dont actually use to compile swc, but we download the crates from the registry, of which you can consult the [deps/swc/Cargo.lock](https://github.com/nodejs/amaro/compare/feat/update-swc-1.7.4?expand=1#diff-59510f2a8e5587434203e81905fa82e1a5780fac007a872563aac41bea8198c8) and [deps/swc/bindings/Cargo.lock](https://github.com/nodejs/amaro/compare/feat/update-swc-1.7.4?expand=1#diff-5ac95dd583c062f3eff03aa649c6a80607a79a0218451715140ac8a645a4f6e0)
- Updates swc to version to v1.7.4

cc @ChALkeR  @nodejs/security-wg 

Fixes: https://github.com/nodejs/amaro/issues/24

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by marco-ippolito** [comment]
when trying to install `wasm-pack` with `--locked` in the docker image
```
RUN cargo install --locked wasm-pack
```

```
19.47    Compiling libz-ng-sys v1.1.15
19.68 error: failed to run custom build command for `libz-ng-sys v1.1.15`
19.68 
19.68 Caused by:
19.68   process didn't exit successfully: `/tmp/cargo-installUL83BC/release/build/libz-ng-sys-aba5baf054df88cc/build-script-build_zng` (exit status: 101)
19.68   --- stdout
19.68   CMAKE_TOOLCHAIN_FILE_aarch64-unknown-linux-gnu = None
19.68   CMAKE_TOOLCHAIN_FILE_aarch64_unknown_linux_gnu = None
19.68   HOST_CMAKE_TOOLCHAIN_FILE = None
19.68   CMAKE_TOOLCHAIN_FILE = None
19.68   CMAKE_GENERATOR_aarch64-unknown-linux-gnu = None
19.68   CMAKE_GENERATOR_aarch64_unknown_linux_gnu = None
19.68   HOST_CMAKE_GENERATOR = None
19.68   CMAKE_GENERATOR = None
19.68   CMAKE_PREFIX_PATH_aarch64-unknown-linux-gnu = None
19.68   CMAKE_PREFIX_PATH_aarch64_unknown_linux_gnu = None
19.68   HOST_CMAKE_PREFIX_PATH = None
19.68   CMAKE_PREFIX_PATH = None
19.68   CMAKE_aarch64-unknown-linux-gnu = None
19.68   CMAKE_aarch64_unknown_linux_gnu = None
19.68   HOST_CMAKE = None
19.68   CMAKE = None
19.68   running: cd "/tmp/cargo-installUL83BC/release/build/libz-ng-sys-25c14643530028d9/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-ng-sys-1.1.15/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=OFF" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-installUL83BC/release/build/libz-ng-sys-25c14643530028d9/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
19.68 
19.68   --- stderr
19.68   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:
19.68 
19.68   failed to execute command: No such file or directory (os error 2)
19.68   is `cmake` not installed?
19.68 
19.68   build script failed, must exit now
19.68   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
19.68 warning: build failed, waiting for other jobs to finish...
25.93 error: failed to compile `wasm-pack v0.13.0`, intermediate artifacts can be found at `/tmp/cargo-installUL83BC`.
25.93 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
------
Dockerfile:35
--------------------
  33 |     COPY deps/swc .
  34 |     
  35 | >>> RUN cargo install --locked wasm-pack
  36 |     
  37 |     WORKDIR /usr/src/amaro/bindings/binding_typescript_wasm
--------------------
ERROR: failed to solve: process "/bin/bash -c cargo install --locked wasm-pack" did not complete successfully: exit code: 101
node:child_process:965
    throw err;
```

**Comment by ChALkeR** [comment]
Will test shortly today

**Comment by kdy1** [comment]
I published 1.7.5, to publish https://github.com/swc-project/swc/pull/9369 and https://github.com/swc-project/swc/pull/9367

**Pull request merged**
