### PR TITLE
chore(tools): fix command injection via __dirname in build process

### PR DESCRIPTION
**Pull request by ChALkeR**
I did not test this / not sure where to run it, please recheck

### CODE REVIEW

**Comment by marco-ippolito** [comment]
if you run `node tools/build-wasm.js` it should re-create the lib folder and run `npm test` to check it works

**Comment by ChALkeR** [comment]
@marco-ippolito will get to my non-laptop setup that has docker a bit later and will then run this on it, thanks!

**Comment by marco-ippolito** [comment]
I tested it and it works, can you amend the commit to match conventional commits so we can merge

**Comment by marco-ippolito** [comment]
I rebase and fixed linting so we can land this

**Review by marco-ippolito — APPROVED** [review]

**Pull request merged**
