### PR TITLE
test: add tests for nativeClassProperties

### PR DESCRIPTION
**Pull request by marco-ippolito**

### CODE REVIEW

**Comment by robpalme** [comment]
The test case is wrong.  The desired outcome is for field initializers to remain as field initializers.

I'm guessing the transforms list needs an extra option: `useDefineForClassFields: true`.

**Comment by robpalme** [comment]
The test output is incorrect.  So we're not picking up the desired new behavior yet.

**Comment by magic-akari** [comment]
The current module relationship is
`binding_typescript_wasm` -> `swc_fast_ts_strip` -> `swc_ecma_transforms_typescript`

Now, the `swc_ecma_transforms_typescript` module has been updated, but no new version has been released yet,
all dependencies are still referencing the old version.

We may need @kdy1 to explain the compilation and update process.

**Comment by robpalme** [comment]
@magic-akari do you know if today's [`@swc/wasm-typescript v1.7.12`](https://www.npmjs.com/package/@swc/wasm-typescript) contains this new option?

**Comment by magic-akari** [comment]
> @magic-akari do you know if today's [`@swc/wasm-typescript v1.7.12`](https://www.npmjs.com/package/@swc/wasm-typescript) contains this new option?

I don't know.

---

There are methods to ensure the use of a local build over crate packages. For details, refer to the script in this CI
https://github.com/swc-project/swc/blob/05961eb018e2e76ed5ef95de9bad923b2fe1df88/.github/workflows/CI.yml#L147-L152

I'm not certain if this is the recommended method.

**Comment by marco-ippolito** [comment]
maybe @kdy1 knows?

**Comment by kdy1** [comment]
Sorry, I missed the email. I'll publish `swc_ecma_transforms_typescript` and `swc_fast_ts_strip` right away.

**Comment by kdy1** [comment]
I published those crates and triggered publish of [`v1.7.14`](https://github.com/swc-project/swc/actions/runs/10453197291)

**Comment by marco-ippolito** [comment]
thank you!

**Pull request merged**
